"""add battle stats and enrichment fields to characters

Revision ID: 3b94b2b11c47
Revises: 
Create Date: 2026-09-07 03:00:35.164623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b94b2b11c47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_english', sa.String(length=500), nullable=True),
    sa.Column('title_japanese', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilist_id'),
    sa.UniqueConstraint('mal_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_japanese', sa.String(length=200), nullable=True),
    sa.Column('manga_id', sa.UUID(), nullable=True),
    sa.Column('universe', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('catchphrases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('weaknesses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('abilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('power_level', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('hax', sa.Integer(), nullable=True),
    sa.Column('battle_iq', sa.Integer(), nullable=True),
    sa.Column('source_api', sa.String(length=50), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilist_id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_universe'), 'characters', ['universe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_universe'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('manga')
    # ### end Alembic commands ###
